const coasterData = [
    {
        "coaster_name": "Kingda Ka",
        "Lat": 40.139426614825204, 
        "Lon": -74.4365807621081,
        "Length": "950 m",
        "Speed": 206,
        "Location": "Six Flags Great Adventure",
        "Status": "Operating",
        "Opening date": "2005-05-21",
        "Type": "Steel – Launched",
        "Manufacturer": "Intamin",
        "Height restriction": "137–196 cm",
        "Model": "Accelerator Coaster",
        "Height": "139 m",
        "Inversions": "0",
        "Lift/launch system": "Hydraulic launch",
        "Cost": "25,000,000 USD",
        "Trains": "4 trains with 5 cars each, 18 riders per train",
        "Park section": "The Golden Kingdom",
        "Duration": "0:28",
        "Capacity": "1400 riders per hour",
        "G-force": "",
        "Designer": "Werner Stengel",
        "Max vertical angle": "90°",
        "Drop": "127 m",
        "Soft opening date": "2005-05-19",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "Flash Pass available",
        "Closing date": "2005-05-19",
        "Opened": "",
        "Replaced by": "",
        "Website": "",
        "Flash Pass Available": "",
        "Must transfer from wheelchair": "Flash Pass available",
        "Theme": "0 to 206 km/h in 3.5 seconds",
        "Single rider line available": "",
        "Restraint Style": "2005",
        "Flash Pass available": "40.1392",
        "Acceleration": "-74.4365",
        "Restraints": "Steel",
        "Name": "2005-05-21",
        "year_introduced": "206 km/h",
        "latitude": "",
        "longitude": "206.0",
        "Type_Main": "km/h",
        "opening_date_clean": "456.0",
        "speed1": "ft",
        "speed2": "",
        "speed1_value": "0",
        "speed1_unit": "",
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Red Force (roller coaster)",
        "Lat": 41.08429688869309, 
        "Lon":  1.1526940956173999,
        "Length": "880 m",
        "Speed": 180,
        "Location": "Ferrari Land",
        "Status": "Operating",
        "Opening date": "2017-04-07",
        "Type": "Steel – Launched",
        "Manufacturer": "Intamin",
        "Height restriction": "140–195 cm",
        "Model": "",
        "Height": "367 ft",
        "Inversions": "0",
        "Lift/launch system": "LSM",
        "Cost": "",
        "Trains": "3 cars, 12 riders per train",
        "Park section": "",
        "Duration": "1200 riders per hour",
        "Capacity": "",
        "G-force": "90°",
        "Designer": "",
        "Max vertical angle": "",
        "Drop": "",
        "Soft opening date": "",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "0 to 180 km/h in 5 seconds",
        "Website": "",
        "Flash Pass Available": "2017",
        "Must transfer from wheelchair": "",
        "Theme": "Steel",
        "Single rider line available": "2017-04-07",
        "Restraint Style": "180 km/h",
        "Flash Pass available": "",
        "Acceleration": "180.0",
        "Restraints": "km/h",
        "Name": "367.5",
        "year_introduced": "ft",
        "latitude": "",
        "longitude": "0",
        "Type_Main": "",
        "opening_date_clean": null,
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Superman: Escape from Krypton",
        "Lat": 34.42420622216382, 
        "Lon": -118.59809083357864,
        "Length": "376.4 m",
        "Speed": 160.9,
        "Location": "Other",
        "Status": "Operating",
        "Opening date": "1997-03-15",
        "Type": "Steel – Launched – Shuttle – Dueling",
        "Manufacturer": "Intamin",
        "Height restriction": "122 cm",
        "Model": "Reverse Freefall Coaster",
        "Height": "126.5 m",
        "Inversions": "0",
        "Lift/launch system": "Linear synchronous motor",
        "Cost": "20,000,000 USD",
        "Trains": "",
        "Park section": "Samurai Summit",
        "Duration": "0:28",
        "Capacity": "1050 riders per hour",
        "G-force": "4.5",
        "Designer": "",
        "Max vertical angle": "90°",
        "Drop": "100 m",
        "Soft opening date": "",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "Flash Pass available",
        "Closing date": "Must transfer from wheelchair",
        "Opened": "",
        "Replaced by": "",
        "Website": "",
        "Flash Pass Available": "0 to 104 mph in 7 seconds",
        "Must transfer from wheelchair": "",
        "Theme": "1997",
        "Single rider line available": "34.425",
        "Restraint Style": "-118.598",
        "Flash Pass available": "Steel",
        "Acceleration": "1997-03-15",
        "Restraints": "160.9 km/h",
        "Name": "",
        "year_introduced": "160.9",
        "latitude": "km/h",
        "longitude": "415.0",
        "Type_Main": "ft",
        "opening_date_clean": "",
        "speed1": "0",
        "speed2": "4.5",
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Steel Dragon 2000",
        "Lat": 35.032967693470674, 
        "Lon": 136.73319273576908,
        "Length": "2479 m",
        "Speed": 152.9,
        "Location": "Nagashima Spa Land",
        "Status": "Operating",
        "Opening date": "2000-08-01",
        "Type": "Steel",
        "Manufacturer": "D. H. Morgan Manufacturing",
        "Height restriction": "140–185 cm",
        "Model": "",
        "Height": "318 ft",
        "Inversions": "0",
        "Lift/launch system": "One lift hill with two chains",
        "Cost": "52,000,000 USD",
        "Trains": "Multiple trains, 28 riders per train",
        "Park section": "",
        "Duration": "4:00",
        "Capacity": "",
        "G-force": "Steve Okamoto",
        "Designer": "68°",
        "Max vertical angle": "93.5 m",
        "Drop": "",
        "Soft opening date": "Out and back",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "2000",
        "Website": "35.0312",
        "Flash Pass Available": "136.7301",
        "Must transfer from wheelchair": "Steel",
        "Theme": "2000-08-01",
        "Single rider line available": "152.9 km/h",
        "Restraint Style": "",
        "Flash Pass available": "152.9",
        "Acceleration": "km/h",
        "Restraints": "318.2",
        "Name": "ft",
        "year_introduced": "",
        "latitude": "0",
        "longitude": "",
        "Type_Main": null,
        "opening_date_clean": null,
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Fury 325",
        "Lat": 35.10570140258403, 
        "Lon": -80.94252277772125,
        "Length": "2012 m",
        "Speed": 153,
        "Location": "Carowinds",
        "Status": "Operating",
        "Opening date": "2015-03-28",
        "Type": "Steel",
        "Manufacturer": "Bolliger & Mabillard",
        "Height restriction": "137 cm",
        "Model": "Hyper Coaster",
        "Height": "99 m",
        "Inversions": "0",
        "Lift/launch system": "Chain lift hill",
        "Cost": "30,000,000 USD",
        "Trains": "3 trains, 32 riders per train",
        "Park section": "Thrill Zone",
        "Duration": "",
        "Capacity": "1470 riders per hour",
        "G-force": "",
        "Designer": "81°",
        "Max vertical angle": "98 m",
        "Drop": "2015-03-25",
        "Soft opening date": "Fast Lane available",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "Fast Lane available",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "",
        "Flash Pass Available": "2015",
        "Must transfer from wheelchair": "35.1055",
        "Theme": "-80.9425",
        "Single rider line available": "Steel",
        "Restraint Style": "2015-03-28",
        "Flash Pass available": "153 km/h",
        "Acceleration": "",
        "Restraints": "153.0",
        "Name": "km/h",
        "year_introduced": "325.0",
        "latitude": "ft",
        "longitude": "",
        "Type_Main": "0",
        "opening_date_clean": "",
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Millennium Force",
        "Lat": 41.4816668466911,
        "Lon": -82.68821643504202,
        "Length": "2010 m",
        "Speed": 150,
        "Location": "Cedar Point",
        "Status": "Operating",
        "Opening date": "2000-05-13",
        "Type": "Steel",
        "Manufacturer": "Intamin",
        "Height restriction": "122–198 cm",
        "Model": "Giga Coaster",
        "Height": "94 m",
        "Inversions": "0",
        "Lift/launch system": "Cable lift hill",
        "Cost": "25,000,000 USD",
        "Trains": "3 trains, 36 riders per train",
        "Park section": "Millennium Midway",
        "Duration": "2:20",
        "Capacity": "1300 riders per hour",
        "G-force": "4.5",
        "Designer": "Werner Stengel",
        "Max vertical angle": "80°",
        "Drop": "91 m",
        "Soft opening date": "2000-05-11",
        "Fast Lane available": "",
        "Replaced": "Giant Wheel",
        "Track layout": "Out and back",
        "Fastrack available": "",
        "Soft opening date.1": "2000-05-11",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "",
        "Flash Pass Available": "",
        "Must transfer from wheelchair": "T-bars With Seatbelt",
        "Theme": "2000",
        "Single rider line available": "41.4817",
        "Restraint Style": "-82.6881",
        "Flash Pass available": "Steel",
        "Acceleration": "2000-05-13",
        "Restraints": "150 km/h",
        "Name": "",
        "year_introduced": "150.0",
        "latitude": "km/h",
        "longitude": "310.0",
        "Type_Main": "ft",
        "opening_date_clean": "",
        "speed1": "0",
        "speed2": "4.5",
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Leviathan (Canada's Wonderland)",
        "Lat": 43.84462591487945, 
        "Lon": -79.54232790421617,
        "Length": "1672 m",
        "Speed": 148,
        "Location": "Canada's Wonderland",
        "Status": "Operating",
        "Opening date": "2012-05-06",
        "Type": "Steel",
        "Manufacturer": "Bolliger & Mabillard",
        "Height restriction": "137–203 cm",
        "Model": "Hyper coaster",
        "Height": "306 ft",
        "Inversions": "0",
        "Lift/launch system": "Chain lift hill",
        "Cost": "28,000,000 USD",
        "Trains": "",
        "Park section": "Medieval Faire",
        "Duration": "3:28",
        "Capacity": "1650 riders per hour",
        "G-force": "4.5",
        "Designer": "Werner Stengel",
        "Max vertical angle": "80°",
        "Drop": "306 ft",
        "Soft opening date": "2012-04-27",
        "Fast Lane available": "",
        "Replaced": "Out and Back",
        "Track layout": "2012-04-27",
        "Fastrack available": "",
        "Soft opening date.1": "Must transfer from wheelchair",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "Lap bar and seat belt",
        "Flash Pass Available": "2012",
        "Must transfer from wheelchair": "43.8445",
        "Theme": "-79.5424",
        "Single rider line available": "Steel",
        "Restraint Style": "2012-05-06",
        "Flash Pass available": "148 km/h",
        "Acceleration": "",
        "Restraints": "148.0",
        "Name": "km/h",
        "year_introduced": "306.1",
        "latitude": "ft",
        "longitude": "",
        "Type_Main": "0",
        "opening_date_clean": "4.5",
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Orion (roller coaster)",
        "Lat": 39.34283232625962, 
        "Lon": -84.262733319824,
        "Length": "1622 m",
        "Speed": 146,
        "Location": "Kings Island",
        "Status": "Operating",
        "Opening date": "2020-07-02",
        "Type": "Steel",
        "Manufacturer": "Bolliger & Mabillard",
        "Height restriction": "137 cm",
        "Model": "Hyper Coaster",
        "Height": "287 ft",
        "Inversions": "0",
        "Lift/launch system": "Chain lift hill",
        "Cost": "30,000,000 USD",
        "Trains": "3 trains, 32 riders per train",
        "Park section": "Area 72",
        "Duration": "3:00",
        "Capacity": "1650 riders per hour",
        "G-force": "",
        "Designer": "85°",
        "Max vertical angle": "91 m",
        "Drop": "2020-07-01",
        "Soft opening date": "",
        "Fast Lane available": "Firehawk Dinosaurs Alive!",
        "Replaced": "2020-07-01",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "2020",
        "Website": "39.3427",
        "Flash Pass Available": "-84.2627",
        "Must transfer from wheelchair": "Steel",
        "Theme": "2020-07-02",
        "Single rider line available": "146 km/h",
        "Restraint Style": "",
        "Flash Pass available": "146.0",
        "Acceleration": "km/h",
        "Restraints": "287.0",
        "Name": "ft",
        "year_introduced": "",
        "latitude": "0",
        "longitude": "",
        "Type_Main": null,
        "opening_date_clean": null,
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Hyperion (roller coaster)",
        "Lat": 50.00121375714698, 
        "Lon": 19.411642915341385,
        "Length": "1450 m",
        "Speed": 142,
        "Location": "Energylandia",
        "Status": "Operating",
        "Opening date": "2018-07-14",
        "Type": "Steel",
        "Manufacturer": "Intamin",
        "Height restriction": "140–195 cm",
        "Model": "Mega coaster",
        "Height": "253 ft",
        "Inversions": "1",
        "Lift/launch system": "Chain lift hill",
        "Cost": "",
        "Trains": "2 trains, 28 riders per train",
        "Park section": "Extreme Zone",
        "Duration": "",
        "Capacity": "1300 riders per hour",
        "G-force": "4.8",
        "Designer": "",
        "Max vertical angle": "85°",
        "Drop": "269 ft",
        "Soft opening date": "",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "2018",
        "Closing date": "Steel",
        "Opened": "2018-07-14",
        "Replaced by": "142 km/h",
        "Website": "",
        "Flash Pass Available": "142.0",
        "Must transfer from wheelchair": "km/h",
        "Theme": "253.0",
        "Single rider line available": "ft",
        "Restraint Style": "",
        "Flash Pass available": "1",
        "Acceleration": "4.8",
        "Restraints": null,
        "Name": null,
        "year_introduced": null,
        "latitude": null,
        "longitude": null,
        "Type_Main": null,
        "opening_date_clean": null,
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Phantom's Revenge",
        "Lat": 40.38922089096194, 
        "Lon": -79.86596410442306,
        "Length": "980 m",
        "Speed": 137,
        "Location": "Kennywood",
        "Status": "Operating",
        "Opening date": "1991-05-10",
        "Type": "Steel",
        "Manufacturer": "D. H. Morgan Manufacturing",
        "Height restriction": "122 cm",
        "Model": "Hyper Coaster",
        "Height": "160 ft",
        "Inversions": "0",
        "Lift/launch system": "Chain lift hill",
        "Cost": "4,600,000 USD",
        "Trains": "2 trains, 28 riders per train",
        "Park section": "Lost Kennywood",
        "Duration": "1:57",
        "Capacity": "1400 riders per hour",
        "G-force": "3.5",
        "Designer": "",
        "Max vertical angle": "52°",
        "Drop": "69 m",
        "Soft opening date": "Laser Loop",
        "Fast Lane available": "Terrain Mega Coaster",
        "Replaced": "2001",
        "Track layout": "",
        "Fastrack available": "2001",
        "Soft opening date.1": "",
        "Closing date": "2001",
        "Opened": "Steel",
        "Replaced by": "1991-05-10",
        "Website": "137 km/h",
        "Flash Pass Available": "",
        "Must transfer from wheelchair": "137.0",
        "Theme": "km/h",
        "Single rider line available": "160.0",
        "Restraint Style": "ft",
        "Flash Pass available": "",
        "Acceleration": "0",
        "Restraints": "3.5",
        "Name": null,
        "year_introduced": null,
        "latitude": null,
        "longitude": null,
        "Type_Main": null,
        "opening_date_clean": null,
        "speed1": null,
        "speed2": null,
        "speed1_value": null,
        "speed1_unit": null,
        "speed_mph": null,
        "height_value": null,
        "height_unit": null,
        "height_ft": null,
        "Inversions_clean": null,
        "Gforce_clean": null
    },
    {
        "coaster_name": "Goliath (Six Flags Magic Mountain)",
        "Lat": 34.427009917864346, 
        "Lon": -118.59771789124913,
        "Length": "400 m",
        "Speed": 137,
        "Location": "Six Flags Magic Mountain",
        "Status": "Operating",
        "Opening date": "February 11, 2000",
        "Type": "Steel",
        "Manufacturer": "Giovanola",
        "Height restriction": "122 cm",
        "Model": "Mega Coaster",
        "Height": "72 m",
        "Inversions": 0,
        "Lift/launch system": "Chain lift hill",
        "Cost": "$30 million",
        "Trains": "3 trains with 5 cars. Riders are arranged 2 across in 3 rows for a total of 30 riders per train.",
        "Park section": "Goliath Plaza",
        "Duration": "3:00",
        "Capacity": "1600 riders per hour",
        "G-force": "",
        "Designer": "Werner Stengel",
        "Max vertical angle": "61°",
        "Drop": "78 m",
        "Soft opening date": "",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "Official website",
        "Flash Pass Available": "",
        "Must transfer from wheelchair": "",
        "Theme": "",
        "Single rider line available": "",
        "Restraint Style": "",
        "Flash Pass available": "",
        "Acceleration": "",
        "Restraints": "",
        "Name": "",
        "year_introduced": 2000,
        "latitude": 34.4269,
        "longitude": -118.5969,
        "Type_Main": "Steel",
        "opening_date_clean": "2000-02-11",
        "speed1": "137 km/h",
        "speed2": "137 km/h",
        "speed1_value": 137.0,
        "speed1_unit": "km/h",
        "speed_mph": "",
        "height_value": 72.0,
        "height_unit": "m",
        "height_ft": "",
        "Inversions_clean": 0,
        "Gforce_clean": ""
    },
    {
        "coaster_name": "Titan (Six Flags Over Texas)",
        "Lat": 32.75572257002504, 
        "Lon": -97.0742012183181,
        "Length": "619 m",
        "Speed": 137,
        "Location": "Six Flags Over Texas",
        "Status": "Operating",
        "Opening date": "April 27, 2001",
        "Type": "Steel",
        "Manufacturer": "Giovanola",
        "Height restriction": "122 cm",
        "Model": "Hyper Coaster",
        "Height": "75 m",
        "Inversions": 0,
        "Lift/launch system": "Chain lift hill",
        "Cost": "",
        "Trains": "3 trains with 5 cars. Riders are arranged 2 across in 3 rows for a total of 30 riders per train.",
        "Park section": "Texas",
        "Duration": "3:30",
        "Capacity": "1600 riders per hour",
        "G-force": "",
        "Designer": "Werner Stengel",
        "Max vertical angle": "",
        "Drop": "78 m",
        "Soft opening date": "April 26, 2001",
        "Fast Lane available": "",
        "Replaced": "Twister",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "April 26, 2001",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "Official website",
        "Flash Pass Available": "Flash Pass Available",
        "Must transfer from wheelchair": "",
        "Theme": "",
        "Single rider line available": "",
        "Restraint Style": "",
        "Flash Pass available": "",
        "Acceleration": "",
        "Restraints": "",
        "Name": "",
        "year_introduced": 2001,
        "latitude": 32.7556,
        "longitude": -97.0742,
        "Type_Main": "Steel",
        "opening_date_clean": "2001-04-27",
        "speed1": "137 km/h",
        "speed2": "137 km/h",
        "speed1_value": 137.0,
        "speed1_unit": "km/h",
        "speed_mph": "",
        "height_value": 75.0,
        "height_unit": "m",
        "height_ft": "",
        "Inversions_clean": 0,
        "Gforce_clean": ""
    },
    {
        "coaster_name": "Formula Rossa",
        "Lat": 24.484390359075295, 
        "Lon": 54.61241043716389,
        "Length": "2,000 m",
        "Speed": 240,
        "Location": "Ferrari World Abu Dhabi",
        "Status": "Operating",
        "Opening date": "4 November 2010",
        "Type": "Steel – Launched",
        "Manufacturer": "Intamin",
        "Height restriction": "140–195 cm",
        "Model": "Accelerator Coaster",
        "Height": "52 m",
        "Inversions": 0,
        "Lift/launch system": "Hydraulic Launch Track",
        "Cost": "",
        "Trains": "4 trains with 4 cars. Riders are arranged 2 across in 2 rows for a total of 16 riders per train.",
        "Park section": "",
        "Duration": "1:32",
        "Capacity": "625 riders per hour",
        "G-force": "4.8",
        "Designer": "",
        "Max vertical angle": "",
        "Drop": "",
        "Soft opening date": "",
        "Fast Lane available": "",
        "Replaced": "",
        "Track layout": "",
        "Fastrack available": "",
        "Soft opening date.1": "",
        "Closing date": "",
        "Opened": "",
        "Replaced by": "",
        "Website": "Official website",
        "Flash Pass Available": "",
        "Must transfer from wheelchair": "",
        "Theme": "",
        "Single rider line available": "",
        "Restraint Style": "",
        "Flash Pass available": "",
        "Acceleration": "0 to 240 km/h in 4.9 seconds",
        "Restraints": "",
        "Name": "",
        "year_introduced": 2010,
        "latitude": 24.4842,
        "longitude": 54.6124,
        "Type_Main": "Steel",
        "opening_date_clean": "2010-11-04",
        "speed1": "240 km/h",
        "speed2": "240 km/h",
        "speed1_value": 240.0,
        "speed1_unit": "km/h",
        "speed_mph": "",
        "height_value": 52.0,
        "height_unit": "m",
        "height_ft": "",
        "Inversions_clean": 0,
        "Gforce_clean": "4.8"
    },
];